/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ */
package cn.zhuatech.esg.service;
import cn.zhuatech.esg.common.BusinessException; import cn.zhuatech.esg.dto.EsgDto.*; import cn.zhuatech.esg.model.*; import cn.zhuatech.esg.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional(readOnly=true) public class EsgService {
    private final DisclosureTaskRepository orders; private final MetricSubmissionRepository reports; private final MetricDefinitionRepository metricDefinition; private final AssuranceFindingRepository assuranceFindings; private final CurrentUserService current;
    public EsgService(DisclosureTaskRepository orders,MetricSubmissionRepository reports,MetricDefinitionRepository metricDefinition,AssuranceFindingRepository assuranceFindings,CurrentUserService current){this.orders=orders;this.reports=reports;this.metricDefinition=metricDefinition;this.assuranceFindings=assuranceFindings;this.current=current;}
    public Dashboard shopfloorDashboard(){String center=current.get().getReportingScopeCode();List<DisclosureTask> list=center==null?orders.findAllByOrderByDueDateAsc():orders.findByReportingScopeCodeOrderByDueDateAsc(center);return dashboard(list);}
    public Dashboard adminDashboard(){return dashboard(orders.findAllByOrderByDueDateAsc());}
    public List<DisclosureTaskView> disclosureTasks(){return orders.findAllByOrderByDueDateAsc().stream().map(this::view).toList();}
    @Transactional public ReportResult report(Long id,ReportRequest request){DisclosureTask order=orders.findById(id).orElseThrow(()->new BusinessException("披露任务不存在"));if(order.getStatus()==DisclosureTask.Status.COMPLETED)throw new BusinessException("已完成任务不能继续反馈");if(order.getCompletedQty()+request.goodQty()>order.getPlannedQty())throw new BusinessException("完成数量不能超过任务剩余数量");order.report(request.goodQty(),request.defectQty());reports.save(new MetricSubmission(order,request.operationName(),request.goodQty(),request.defectQty(),current.get().getFullName(),request.remark()));return new ReportResult(order.getOrderNo(),order.getCompletedQty(),order.getDefectQty(),progress(order),order.getStatus().name());}
    private Dashboard dashboard(List<DisclosureTask> list){int planned=list.stream().mapToInt(DisclosureTask::getPlannedQty).sum(),done=list.stream().mapToInt(DisclosureTask::getCompletedQty).sum(),defects=list.stream().mapToInt(DisclosureTask::getDefectQty).sum();int rate=planned==0?0:Math.round(done*100f/planned);List<Metric> metrics=List.of(new Metric("今日披露",String.format("%,d",planned),list.size()+" 张披露任务","blue"),new Metric("披露完成率",rate+"%",String.format("%,d / %,d",done,planned),"green"),new Metric("结果合规率",String.format("%.1f%%",done+defects==0?100d:done*100d/(done+defects)),defects+" 项异常","warn"),new Metric("指标定义异常",metricDefinition.countByStatus(MetricDefinition.Status.ALARM)+"",assuranceFindings.countByResult(AssuranceFinding.Result.PENDING)+" 项待鉴证","red"));return new Dashboard(metrics,list.stream().map(this::view).toList(),metricDefinition.findAllByOrderByCodeAsc().stream().map(e->new MetricDefinitionView(e.getCode(),e.getName(),e.getReportingScope().getName(),e.getStatus().name(),e.getOee(),e.getLastHeartbeat())).toList(),assuranceFindings.findTop10ByOrderByIdDesc().stream().map(i->new AssuranceFindingView(i.getAssuranceFindingNo(),i.getDisclosureTask().getOrderNo(),i.getDisclosureTask().getProductName(),i.getAssuranceFindingType(),i.getAssuranceFindingQty(),i.getDefectQty(),i.getResult().name(),i.getInspector())).toList());}
    private DisclosureTaskView view(DisclosureTask o){return new DisclosureTaskView(o.getId(),o.getOrderNo(),o.getProductCode(),o.getProductName(),o.getReportingScope().getName(),o.getReportingScope().getWorkshop(),o.getPlannedQty(),o.getCompletedQty(),o.getDefectQty(),o.getDueDate(),o.getStatus().name(),o.getBatchNo(),progress(o));}
    private int progress(DisclosureTask o){return o.getPlannedQty()==0?0:Math.min(100,Math.round(o.getCompletedQty()*100f/o.getPlannedQty()));}
}
